### ISSUE TITLE
wrong number of arguments (1 for 2)

### ISSUE THREAD

**Issue by zacksiri** [n8/multi_fetch_fragments#18] opened 2013-04-18 09:25 UTC
I am getting this error after upgrading to 0.0.14 

here is the line in question

``` ruby
<%= render partial: 'activity', collection: @activities, cache: true %>
```

**Comment by zacksiri** [comment] 2013-04-18 10:14
stack trace shows this 

``` ruby
  (gem) multi_fetch_fragments-0.0.14/lib/multi_fetch_fragments.rb:29:in `block in render_collection_with_multi_fetch_cache'
  (gem) multi_fetch_fragments-0.0.14/lib/multi_fetch_fragments.rb:24:in `render_collection_with_multi_fetch_cache'
```

**Comment by nickurban** [comment] 2013-04-19 20:21
I'm having the same problem.

**Comment by n8** [comment] 2013-04-19 20:26
What version of Rails are you guys using?

**Comment by nickurban** [comment] 2013-04-19 21:07
ruby '2.0.0'
gem 'rails', '3.2.13'

**Comment by zacksiri** [comment] 2013-04-20 02:20
Yep me too

**Comment by samratjp** [comment] 2013-05-03 20:50
Me too - same version of Rails but 1.9.3 ruby. Any updates on this guys?

**Comment by cpuguy83** [comment] 2013-05-04 02:13
I believe this is coming from cache_digests v 0.3.0.
The issue is on line 29 of multi_fetch_fragments.rb

``` ruby
key_with_optional_digest = @view.fragment_name_with_digest(key)
```

@view.fragment_name_with_digest is looking for a second argument (dependencies)

I've tried fooling around with it but ran into other issues.

**Comment by n8** [comment] 2013-05-06 01:18
I think I have this fixed now. To deal with that cache_digests change I now make this gem do this: 

``` ruby
key_with_optional_digest = @view.fragment_name_with_digest(key, @view.view_cache_dependencies)
```

**Closed as completed by n8** 2013-05-06 01:18 UTC

**Comment by cpuguy83** [comment] 2013-05-06 13:37
Now getting an issue in redis-store: `undefined method  'match' for #<Array:0x007f8419d2e3e0>`

I copied in the cache keys that I was trying to pull for my fragments and directly called `Rails.cache.read_mutli *my_keys` and it does work... so it looks like we need to splat the key argument now.
